username = "alejandra.caceres@ariadnacg.com"
password = "Ariadna123456789"
# key_file_location = '/connection/client_secret.json'

# Production
key_file_location = '/connection/mediamath_data.json'
scopes = ['https://www.googleapis.com/auth/drive',
          'https://www.googleapis.com/auth/spreadsheets']
client_id = ''
client_secret = ''
access_token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik0wVTBRa1U1TWpORE5rTTVNakZCTUVaQ05EZEJNa00wTjBReE5EUkNPRUV4T0RJd05EZ3hRdyJ9.eyJodHRwczovL2FwaS5tZWRpYW1hdGguY29tL25pY2tuYW1lIjoianVhbi5lc3Bpbm9zYUBhcmlhZG5hY2cuY29tIiwiaHR0cHM6Ly9hcGkubWVkaWFtYXRoLmNvbS91c2VyX2lkIjoyOTYzMCwiaXNzIjoiaHR0cHM6Ly9hdXRoLm1lZGlhbWF0aC5jb20vIiwic3ViIjoiYXV0aDB8Mjk2MzAiLCJhdWQiOiJodHRwczovL2FwaS5tZWRpYW1hdGguY29tLyIsImlhdCI6MTU2Mjk2Mjg5NywiZXhwIjoxNTYzMDQ5Mjk3LCJhenAiOiJtNk5ad3pOSmJXUWszdnpZYTBBbEhMR1dVUk01T3N4UCIsInNjb3BlIjoiY3JlYXRlOkRNUC1BdWRpZW5jZVZlbmRvciByZWFkOkJPRiByZWFkOmV4Y2hhbmdlLXJhdGVzIHJlYWQ6Y2FtcGFpZ25zIHdyaXRlOmNhbXBhaWducyBjcmVhdGU6dXNlcnMgd3JpdGU6dXNlcnMgcmVhZDp1c2VycyIsImd0eSI6InBhc3N3b3JkIn0.pBR8ODcOAtJM-Cl2n329LsJwhe8vjpqWMrW2hqD6xhdDVGzBpCcoCPrOT7tmU9vqckCxv6-QCm_RZ3OwSASkKCNgXXBRgV7xGH3jigsaJLY9xLVzyFINCUP7UlGPTPbYhx8hhoncJvXj_SaZYLp-olIoaqiIKTPaoFBKDXumJbkaJ7beK_pRayIpnhmknO6QIjxxtgFROkv2YXjiKMZFiqeQ3vlpTTGAPqAsheWuI1rAESzyBPUPnRhFKri-GkzCMGHu9m6rTFcoCvGtjOL9htwY0AVihYQD8q-JznjjlLEaJLiJqdJh47T0DiMRUmVi4ere2N75APlqALSwENd1xw"
